---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Tenant subnet intrastructure CloudFormation template"
Parameters:
  ASI:
    Type: String
    MinLength: 3
    MaxLength: 4
    Description: "asi - must be lower-case, limit 4 characters"
    AllowedPattern: "[a-z]*"
  Environment:
    Type: String
    MinLength: 3
    MaxLength: 4
    Description: "environment (dev|itg|cat|prod) - must be lower-case, limit 4 characters"
    AllowedPattern: "[a-z]*"
  Owner:
    Type: String
    Description: "email address of the the Owner of this stack"
    Default: "admin@root.com"
    AllowedPattern: "^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$"
  vpcid:
    Description: VPC Id
    Type: AWS::EC2::VPC::Id
  privateacidr:
    Type: String
    Description: CIDR to use for private subnet a.
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/24
    Default: 10.15.0.0/23
  privatebcidr:
    Type: String
    Description: CIDR to use for private subnet b.
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/24
    Default: 10.15.2.0/23
  transitGatewayId:
    Type: String
    Description: "transit gateway id to attach to"    
  transitgatewayname:
    Type: String
    Description: "name of transit gateway"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
        - ASI
        - Environment
        - Owner
      - Label:
          default: "Network Configuration"
        Parameters:
        - vpcid
        - privateacidr
        - privatebcidr
        - transitGatewayId
        - transitgatewayname
    ParameterLabels:
      vpcid:
        default: "VPC to create subnets in"

Resources:
  SubnetA: # Private Subnet for App Env in AZ - A
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: !Ref privateacidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref vpcid
      Tags:
        -
          Key: "Name"
          Value: "private-a-sn"
        -
          Key: "Project"
          Value: !Ref ASI
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Owner"
          Value: !Ref Owner

  SubnetB: # Private Subnet for App Env in AZ - B 
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ]
      CidrBlock: !Ref privatebcidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref vpcid
      Tags:
        -
          Key: "Name"
          Value: "private-b-sn"
        -
          Key: "Project"
          Value: !Ref ASI
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Owner"
          Value: !Ref Owner

  RouteTablePrivate:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref vpcid
      Tags:
        -
          Key: "Name"
          Value: "private-rt"
        -
          Key: "Project"
          Value: !Ref ASI
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Owner"
          Value: !Ref Owner

  SubnetARouteTableAssociation: # Associates the subnet with a route table - Needed for Transit Gateway
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePrivate
      SubnetId: !Ref SubnetA

  SubnetBRouteTableAssociation: # Associates the subnet with a route table - Needed for Transit Gateway
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePrivate
      SubnetId: !Ref SubnetB

  TransitGatewayAttachment:
    Type: "AWS::EC2::TransitGatewayAttachment"
    Properties:
      SubnetIds:
        - !Ref SubnetA
        - !Ref SubnetB
      Tags: 
        - Key: "Name"
          Value: !Ref transitgatewayname
        -
          Key: "Project"
          Value: !Ref ASI
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Owner"
          Value: !Ref Owner
      TransitGatewayId: !Ref transitGatewayId
      VpcId: !Ref vpcid

  DefaultRoute:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: !Ref transitGatewayId
      RouteTableId: !Ref RouteTablePrivate

Outputs:
  privatesubneta:
    Description: ID of Private Subnet - A
    Value: !Ref SubnetA
    Export: # added to export
      Name: privatesubneta
  privatesubnetb:
    Description: ID of Private Subnet - B
    Value: !Ref SubnetB
    Export: # added to export
      Name: privatesubnetb
  routetableprivate:
    Description: "id of private a route table"
    Value: !Ref RouteTablePrivate
    Export: 
      Name: routetableprivate