language: python
python:
  - "3.6"
install:
  - pip install cfn-lint
script:
  - cfn-lint -i W -t ./*.yaml
  - cfn-lint -i W -t common/*.yaml
  - cfn-lint -i W -t misc/*.yaml
  - cfn-lint -i W -t start_here/*.yaml
  - cfn-lint -i W -t tenantVpc/*.yaml
  - cfn-lint -i W -t transitVpc/*.yaml
