---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3BucketURL:
    Type: String
    Description: "URL of S3 bucket that project files are hosted in."
    Default: "https://s3.amazonaws.com/fortunecookiezen-stack-templates-us-east-1"
  ASI:
    Type: String
    MinLength: 3
    MaxLength: 4
    Description: "ASI Prefix for buckets"
    AllowedPattern: "[a-z-]*"
    Default: "tnt"
  vpccidr:
    Type: String
  appacidr:
    Type: String
  appbcidr:
    Type: String
  privateacidr:
    Type: String
  privatebcidr:
    Type: String

Resources:
  TenantVpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["", [!Ref "S3BucketURL", "/common/01vpc.yaml"]]
      Parameters:
        vpccidr: !Ref vpccidr
        ASI: !Ref ASI
  TenantSubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["", [!Ref "S3BucketURL", "/tenantVpc/02tenantsubnets.yaml"]]
      Parameters:
        vpcid: !GetAtt ["TenantVpcStack", "Outputs.VpcId"]
        appacidr: !Ref appacidr
        appbcidr: !Ref appbcidr
        privateacidr: !Ref privateacidr
        privatebcidr: !Ref privatebcidr
Outputs:
  TenantVpcStack:
    Value: !Ref TenantVpcStack
  TenantSubnetStack:
    Value: !Ref TenantSubnetStack
