---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3BucketURL:
    Type: String
    Description: "URL of S3 bucket that project files are hosted in."
    Default: "https://s3.amazonaws.com/fortunecookiezen-stack-templates-us-east-1"
Resources:
  TransitVpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["", [!Ref "S3BucketURL", "/common/01vpc.yaml"]]
      Parameters:
        vpccidr: "10.15.0.0/22"
  TransitSubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["", [!Ref "S3BucketURL", "/transitVpc/02transitsubnets.yaml"]]
      Parameters:
        vpcid: !GetAtt ["TransitVpcStack", "Outputs.VpcId"]
        publicacidr: "10.15.0.0/25"
        publicbcidr: "10.15.0.128/25"
        privateacidr: "10.15.2.0/24"
        privatebcidr: "10.15.3.0/24"
Outputs:
  TransitVpcStack:
    Value: !Ref TransitVpcStack
  TransitSubnetStack:
    Value: !Ref TransitSubnetStack
