---
AWSTemplateFormatVersion: '2010-09-09'
Description: "S3 Bucket to hold CloudFormation templates for infrastructure creation. Run
this template first, then upload the CloudFormation templates to this bucket based on the
repository structure"

Parameters:
  ASI:
    Type: String
    MinLength: 3
    MaxLength: 4
    Description: "asi - must be lower-case, limit 4 characters"
    AllowedPattern: "[a-z]*"
  Environment:
    Type: String
    MinLength: 3
    MaxLength: 7
    Description: "environment (nonprod|dev|itg|cat|prod) - must be lower-case, limit 7 characters"
    AllowedPattern: "[a-z]*"
  Owner:
    Type: String
    Description: "email address of the the Owner of this stack"
    Default: "admin@root.com"
    AllowedPattern: "^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
        - ASI
        - Environment
        - Owner

Resources:
  S3TemplateBucket:
    DeletionPolicy: Retain
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join
      - '-'
      - -  !Ref ASI
        -  !Ref Environment
        -  !Ref 'AWS::Region'
        -  templatebucket
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      Tags:
        -
          Key: "ManagedBy"
          Value: !Ref AWS::StackName

  TemplateBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3TemplateBucket
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - 's3:GetObject'
              - 's3:GetObjectAcl'
            Effect: "Allow"
            Resource: 
              Fn::Join: 
                - ""
                - 
                  - "arn:aws:s3:::"
                  - 
                    Ref: "S3TemplateBucket"
                  - "/*"
            Principal:
              AWS: 
              - 'edit_me'
              - 'edit_me'

Outputs:
  templatebucketurl:
    Description: Deploy templates to this bucket
    Value: !GetAtt S3TemplateBucket.DomainName
    Export: # added to export
      Name: templatebucketurl

