---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Transit gateway and route table CloudFormation template"
Parameters:
  vpcid:
    Description: "VPC Id"
    Type: AWS::EC2::VPC::Id
  privatesubneta:
    Type: String
  privatesubnetb:
    Type: String
Resources:
  TransitGateway:
    Type: "AWS::EC2::TransitGateway"
    Properties:
      AutoAcceptSharedAttachments: "enable"
      DefaultRouteTableAssociation: "enable"
      DefaultRouteTablePropagation: "enable"
      DnsSupport: "enable"
      VpnEcmpSupport: "enable"
      Tags:
        -
          Key: "Name"
          Value: "transitgw"

  TransitGatewayAttachment:
    Type: "AWS::EC2::TransitGatewayAttachment"
    Properties:
      SubnetIds:
        - !Ref privatesubneta
        - !Ref privatesubnetb
      TransitGatewayId: !Ref TransitGateway
      VpcId: !Ref vpcid
      Tags:
        -
          Key: "Name"
          Value: "transitgwAttachment"

Outputs:
  transitgatewayid:
    Description: ID of Shared Infrastructure VPC
    Value: !Ref TransitGateway
    Export: # added to export
      Name: transitgatewayid
