---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Transit gateway and route table CloudFormation template"
Parameters:
  ASI:
    Type: String
    MinLength: 2
    MaxLength: 4
    Description: "asi - must be lower-case, limit 4 characters"
    AllowedPattern: "[a-z]*"
  Environment:
    Type: String
    MinLength: 3
    MaxLength: 7
    Description: "environment (nonprod|prod) - must be lower-case, limit 7 characters"
    AllowedPattern: "[a-z]*"
  Owner:
    Type: String
    Description: "email address of the the Owner of this stack"
    Default: "admin@root.com"
    AllowedPattern: "^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
        - ASI
        - Environment
        - Owner

Resources:
  TransitGateway:
    Type: "AWS::EC2::TransitGateway"
    Properties:
      AutoAcceptSharedAttachments: "enable"
      DefaultRouteTableAssociation: "enable"
      DefaultRouteTablePropagation: "enable"
      DnsSupport: "enable"
      VpnEcmpSupport: "enable"
      Tags:
        -
          Key: "Name"
          Value: !Join ["-", [!Ref ASI, !Ref Environment, "tgw"]]
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Owner"
          Value: !Ref Owner

  TransitGatewayAttachment:
    Type: "AWS::EC2::TransitGatewayAttachment"
    Properties:
      SubnetIds:
        - !ImportValue privatesubneta
        - !ImportValue privatesubnetb
      TransitGatewayId: !Ref TransitGateway
      VpcId: !ImportValue VpcId
      Tags:
        -
          Key: "Name"
          Value: !Join ["-", [!Ref ASI, !Ref Environment, "tga"]]
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Owner"
          Value: !Ref Owner

Outputs:
  transitgatewayid:
    Description: ID of TransitGateway
    Value: !Ref TransitGateway
    Export: # added to export
      Name: transitgatewayid
