---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Common VPC intrastructure CloudFormation template"
Parameters:
  vpccidr:
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/16
    Default: 10.15.0.0/22
  ASI:
    Type: String
    MinLength: 3
    MaxLength: 4
    Description: "asi Prefix for buckets - must be lower-case, limit 4 characters"
    AllowedPattern: "[a-z]*"
  Environment:
    Type: String
    MinLength: 3
    MaxLength: 4
    Description: "environment (dev|cat|prod) - must be lower-case, limit 4 characters"
    AllowedPattern: "[a-z]*"
  Owner:
    Type: String
    Description: "email address of the the Owner of this stack"
    Default: "admin@root.com"
    AllowedPattern: "^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
        - ASI
        - Environment
        - Owner
      - Label:
          default: "Network Configuration"
        Parameters:
        - vpccidr
    ParameterLabels:
      vpccidr:
        default: "VPC cidr block"

Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref vpccidr
      EnableDnsHostnames: true
      Tags:
        -
          Key: "Name"
          Value: !Join
          - '-'
          - -  !Ref AWS::Region
            -  vpc
        -
          Key: "Project"
          Value: !Ref ASI
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Owner"
          Value: !Ref Owner

  S3LogBucket:
    DeletionPolicy: Delete
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join
      - '-'
      - -  !Ref AWS::AccountId
        -  !Ref AWS::Region
        -  !Ref ASI
        -  logbucket
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        -
          Key: "ManagedBy"
          Value: !Ref AWS::StackName
        -
          Key: "Project"
          Value: !Ref ASI
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Owner"
          Value: !Ref Owner

  S3ObjectBucket:
    DeletionPolicy: Delete
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join
      - '-'
      - -  !Ref AWS::AccountId
        -  !Ref AWS::Region
        -  !Ref ASI
        -  deploymentbucket
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      Tags:
        -
          Key: "ManagedBy"
          Value: !Ref AWS::StackName
        -
          Key: "Project"
          Value: !Ref ASI
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Owner"
          Value: !Ref Owner

  VPCDefaultSecurityGroupIngress:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !GetAtt [VPC, DefaultSecurityGroup]
      IpProtocol: "-1"
      ToPort: -1
      FromPort: -1
      CidrIp: 10.0.0.0/8

Outputs:
  VpcId:
    Description: ID of Shared Infrastructure VPC
    Value: !Ref VPC
    Export: # added to export
      Name: VpcId
  logbucketurl:
    Description: Account Log Bucket
    Value: !GetAtt S3LogBucket.DomainName
    Export: # added to export
      Name: logbucketurl
  objectbucketurl:
    Description: Account Deployment Bucket
    Value: !GetAtt S3ObjectBucket.DomainName
    Export: # added to export
      Name: objectbucketurl
