---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Common VPC intrastructure CloudFormation template"
Parameters:
  vpccidr:
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/16
    Default: 10.15.4.0/22
Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref vpccidr
      EnableDnsHostnames: true
      Tags:
        -
          Key: "Name"
          Value: !Join
          - '-'
          - -  !Ref AWS::Region
            -  vpc
  S3LogBucket:
    DeletionPolicy: Delete
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join
      - '-'
      - -  !Ref AWS::AccountId
        -  !Ref AWS::Region
        -  logbucket
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        -
          Key: "ManagedBy"
          Value: !Ref AWS::StackName
  S3ObjectBucket:
    DeletionPolicy: Delete
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join
      - '-'
      - -  !Ref AWS::AccountId
        -  !Ref AWS::Region
        -  deploymentbucket
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        -
          Key: "ManagedBy"
          Value: !Ref AWS::StackName
  VPCDefaultSecurityGroupIngress:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !GetAtt [VPC, DefaultSecurityGroup]
      IpProtocol: "-1"
      ToPort: -1
      FromPort: -1
      CidrIp: 10.0.0.0/8

  SG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Ref "AWS::StackName"
      GroupDescription: !Join ["", ["Stack ", !Ref "AWS::StackId", " VPC SecurityGroup"]]
      VpcId: !Ref VPC
      SecurityGroupIngress:
        -
          CidrIp: 10.0.0.0/8
          IpProtocol: "-1"
          ToPort: -1
          FromPort: -1
      SecurityGroupEgress:
        -
          CidrIp: 0.0.0.0/0
          ToPort: -1
          IpProtocol: "-1"
      Tags:
        -
          Key: "Name"
          Value: "use me"


Outputs:
  VpcId:
    Description: ID of Shared Infrastructure VPC
    Value: !Ref VPC
    Export: # added to export
      Name: VpcId
  logbucketurl:
    Description: Shared Infrastructure App Bucket
    Value: !GetAtt S3LogBucket.DomainName
    Export: # added to export
      Name: logbucketurl
  objectbucketurl:
    Description: Shared Infrastructure App Bucket
    Value: !GetAtt S3ObjectBucket.DomainName
    Export: # added to export
      Name: objectbucketurl
